<?php

/** @generate-class-entries */

// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

function exciplex_set_timeout(callable $callable, float $interval): void {}

function exciplex_set_interval(callable $callable, float $initialDelay, float $interval): void {}


