package exciplex

// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

// #include <stdlib.h>
// #include "exciplex.h"
import "C"
import (
	_ "runtime/cgo"
	"unsafe"

	"github.com/dunglas/frankenphp"
)

func init() {
	frankenphp.RegisterExtension(unsafe.Pointer(&C.exciplex_module_entry))
}

//export go_exciplex_set_timeout
func go_exciplex_set_timeout(callback *C.zval, interval float64) {
	SetTimeout(callback, interval)
}

//export go_exciplex_set_interval
func go_exciplex_set_interval(callback *C.zval, initialDelay float64, interval float64) {
	SetInterval(callback, initialDelay, interval)
}
